#!/usr/bin/python
import sys
import os
import argparse
import subprocess
import socket
import json

if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser(prog='spacenctl',
                                         formatter_class=lambda prog:
                                             argparse.HelpFormatter(prog, max_help_position=42))
    
    arg_parser.add_argument("command",
                            help="command to be executed: enable/disable/start/stop")
    
    arg_parser.add_argument("handler",
                            help="handler on which the command is executed")
    
    args = arg_parser.parse_args()
    
    dummy_conn = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    dummy_conn.connect(("localhost", 3001))
    
    if args.command ==  "start":
        data = { "command": "start", "handler": args.handler }
        dummy_conn.send(json.dumps(data).encode("utf-8"))
        dummy_conn.close()
    elif args.command == "stop":
        data = { "command": "stop", "handler": args.handler }
        dummy_conn.send(json.dumps(data).encode("utf-8"))
        dummy_conn.close()
    elif args.command == "enable":
        pass
    elif args.command == "disable":
        pass
    else:
        print("unknown command")
